[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = "cd carti && cd carti && gunicorn carti.wsgi:application --bind 0.0.0.0:$PORT" 